# nmake makefile
#
# Tools used:
#  Compile::Watcom Resource Compiler
#  Compile::GNU C
#  Make: nmake or GNU make
all : pmcolour.exe

pmcolour.exe : pmcolour.obj pmcolour.res pmcolour.def
	gcc -Zomf pmcolour.obj pmcolour.res pmcolour.def -o pmcolour.exe
	wrc pmcolour.res

pmcolour.obj : pmcolour.c pmcolour.h
	gcc -Wall -Zomf -c -O1 pmcolour.c -o pmcolour.obj

pmcolour.res: pmcolour.rc pmcolour.dlg pmcolour.h 
	wrc -r pmcolour.rc 

clean :
	rm -rf *exe *RES *obj